models/Category.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property string $name
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Post[] $posts
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nama'], 'required'],
            [['created_at', 'updated_at'], 'safe'],
            [['nama'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[Posts]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPosts()
    {
        return $this->hasMany(Post::className(), ['category_id' => 'id']);
    }


    public function behaviors(){    
        return [        
            TimestampBehavior::className(),  
              
        ];
    }

}

controllers/CategoryController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\Category;
use app\models\CategorySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessRule;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                
                'rules' => [
                    [
                        'allow' => true,
                        /*'roles' => ['?','@'],*/
                        'matchCallback' => function ($rule, $action) {
                            $moduleID = $action->controller->module->id;
                            $controllerID = $action->controller->id;
                            $actionID = $action->id;
                            $userID = \Yii::$app->user->id;
                            $auth = \app\models\Auth::find()
                                ->where([
                                    'module' => $moduleID,
                                    'controller' => $controllerID,
                                    'action' => $actionID,
                                    'user_id' => $userID,
                                ])
                                ->count();
                            if($auth>0) return true;
                        }
                    ],
                ],

                /*'denyCallback' => function ($rule, $action) {
                throw new \yii\web\ForbiddenHttpException('Anda tidak diizinkan untuk mengakses halaman '.$action->id.' ini!');
                }
*/
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if(Yii::$app->request->isAjax)
        {
            return $this->renderAjax('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
        else{
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
        
    }

    public function actionCheck()
    {
        $category = Category::find()->select('id')->orderBy('id DESC')->one();
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return ['lastId'=>$category->id];

    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if(Yii::$app->request->isAjax)
        {
            return $this->renderAjax('view', [
            'model' => $this->findModel($id),
            ]);
        }
        else
        {
            return $this->render('view', [
            'model' => $this->findModel($id),
            ]);
        }
        
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success','Data berhasil disimpan');
            if(Yii::$app->request->isAjax)
            {
                $model = new Category();
                return $this->renderAjax('create',['model' => $model,
                ]);
            }
            else{
                return $this->redirect(['view', 'id' => $model->id]);
            }
           
        } else {
            if(Yii::$app->request->isAjax){
                return $this->renderAjax('create', [
                    'model' => $model,
                ]);
            }
            else{
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success','Data berhasil disimpan');
            if(Yii::$app->request->isAjax){
                return $this->renderAjax('update',['model' => $model,
                ]);
            }
            else{
                return $this->redirect(['view', 'id' => $model->id]);
            }
            
        }
        else{
            if(Yii::$app->request->isAjax){
            return $this->renderAjax('update', [
                    'model' => $model,
                ]);
            }
            else{
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        //return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    public function actionImport()
    {
        $modelImport = new \yii\base\DynamicModel([
            'fileImport' => 'File Import',
        ]);

        $modelImport->addRule(['fileImport'], 'required');
        $modelImport->addRule(['fileImport'], 'file',['extensions'=>'xls,xlsx'], ['maxSize'=>1024*1024]);

        if(Yii::$app->request->post()){
            $modelImport->fileImport = \yii\web\UploadedFile::getInstance($modelImport, 'fileImport');
            if($modelImport->fileImport && $modelImport->validate()){
                $inputFileType = \PHPExcel_IOFactory::identify($modelImport->fileImport->tempName);

                $objReader = \PHPExcel_IOFactory::createReader($inputFileType);
                $objPHPExcel = $objReader->load($modelImport->fileImport->tempName);
                $sheetData = $objPHPExcel->getActiveSheet()->toArray(null,true,true,true);

                $baseRow = 3;
                while (!empty($sheetData[$baseRow]['A'])) {
                   $model = new Category();
                   $model->name = (string)$sheetData[$baseRow]['A'];
                   $model->save();
                   $baseRow++;
                }
                Yii::$app->getSession()->setFlash('success','Success');
            }
            else{
                Yii::$app->getSession()->setFlash('error','Error');
            }
        }

        return $this->render('import',[
            'modelImport' => $modelImport,
        ]);
    }


    public function actionExportExcel()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        $objReader = \PHPExcel_IOFactory::createReader('Excel2007');
        $template = Yii::getAlias('@app/views/category').'/export.xlsx';
        $objPHPExcel = $objReader->load($template);
        $objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(\PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
        $objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(\PHPExcel_Worksheet_PageSetup::PAPERSIZE_FOLIO);
        $baseRow=3; // line 2
        foreach($dataProvider->getModels() as $category){
            $objPHPExcel->getActiveSheet()->setCellValue('A'.$baseRow, $baseRow-2);
            $objPHPExcel->getActiveSheet()->setCellValue('B'.$baseRow, $category->nama);
            $baseRow++;
        }
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="export.xlsx"');
        header('Cache-Control: max-age=0');
        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, "Excel2007");
        $objWriter->save('php://output');
        exit;
    }

    public function actionExportExcel2()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        // Initalize the TBS instance
        $OpenTBS = new \hscstudio\export\OpenTBS; // new instance of TBS
        // set template
        $template = Yii::getAlias('@app/views/category').'/export2.xlsx';
        // Also merge some [onload] automatic fields (depends of the type of document).
        $OpenTBS->LoadTemplate($template);
        //$OpenTBS->VarRef['modelName']= "Category";
        $data = [];
        $no=1;
        foreach($dataProvider->getModels() as $category){
            $data[] = [
                'no'=>$no++,
                'nama'=>$category->nama,
            ];

views/category/_export.php
<!DOCTYPE html>
<html>
<head>
    <title>Data Category</title>
    <style type="text/css">
    .page{padding:2cm;}
    table{border-spacing:0;border-collapse: collapse;width:100%;}
    table td, table th{border: 1px solid #ccc;}
    </style>
</head>
<body>    
    <div class="page">    
        <h1>Data Category</h1>
        <table border="0">
        <tr>
                <th>No</th>
                <th>Nama</th>
        </tr>
        <?php
        $no = 1;
        foreach($dataProvider->getModels() as $category){ 
        ?>
        <tr>
                <td><?= $no++ ?></td>
                <td><?= $category->nama ?></td>
        </tr>
        <?php
        }
        ?>
        </table>
    </div>   
</body>
</html>

views/category/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
Pjax::begin([
    'id'=>'pjax-form','timeout'=>false,
]);
/* @var $this yii\web\View */
/* @var $model app\models\Category */
/* @var $form yii\widgets\ActiveForm */
?>

    <?php
        if(Yii::$app->request->isAjax)
            echo \app\widgets\Alert::widget();
    ?>

    <?php $form = ActiveForm::begin([
            'options' => ['data-pjax' =>true]
        ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
    
       <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>

        <?= Html::a('Back', ['index'], ['class' => 'btn btn-success',
            'onclick'=>'
          $("#categoryModal").modal("hide");
          return false;
        '
        ])?>
    </div>

    <?php ActiveForm::end(); ?>
<?php Pjax::end(); ?>

views/category/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CategorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/category/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = 'Create Category';
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/category/import.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>


<h1>Import Data</h1>
<?php
$form = ActiveForm::begin([
	'options' =>['enctype' => 'multipart/form-data'],
]) ?>


<?= $form->field($modelImport,'fileImport')->fileInput() ?>
<?= Html::submitButton('Import', ['class'=>'btn btn-primary']) ?>

<?php ActiveForm::end() ?>

views/category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use hscstudio\mimin\components\Mimin;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Categories';
$this->params['breadcrumbs'][] = $this->title;


 Modal::begin([
        'id' => 'categoryModal',
    ]);
        Pjax::begin([
            'id'=>'pjax-modal','timeout'=>false,
            'enablePushState'=>false,
            'enableReplaceState'=>false,
        ]);

        Pjax::end();
    Modal::end();

     


?>

<div class="category-index">
    

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php if((Mimin::checkRoute($this->context->id.'/create'))){
                echo Html::a('Create Category', ['create'], ['class' => 'btn btn-success',
                    /*'data-toggle' =>"modal",
                    'data-target'=>"#categoryModal",*/
                ]);

                echo Html::a('Export Excel',['export-excel'], ['class'=>'btn btn-info']); 

                echo Html::a('Export Excel2', ['export-excel2'], ['class'=>'btn btn-primary']);
                echo Html::a('Export Word', ['export-word'], ['class'=>'btn btn-warning']);

                /*echo Html::a('Export PDF', ['export-pdf'], ['class'=>'btn btn-success']);  */

            }
         ?>

        
    </p>
<!-- 
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
 -->
<?php 
    Pjax::begin(['timeout'=>false, 'id'=>'gridview']); 
?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'nama',
            'created_at:datetime',
            //'updated_at',

            ['class' => 'yii\grid\ActionColumn',
             'buttons'=>[
                'view' => function($url, $model){
                    $icon='<span class="glyphicon glyphicon-eye-open"></span>';
                    return Html::a($icon,$url, [
                        'data-toggle'=>"modal",
                        'data-target'=>"#categoryModal",
                    ]);
                },
                'update' => function ($url, $model){
                    $icon='<span class="glyphicon glyphicon-pencil"></span>';
                    return Html::a($icon, $url, [
                        'data-toggle' =>"modal",
                        'data-target'=>"#categoryModal",
                    ]);
                },
                'delete' => function ($url, $model){
                    $icon='<span class="glyphicon glyphicon-trash"></span>';
                    return Html::a($icon,$url, [
                        'class'=>'pjaxDelete'
                    ]);
                }

             ]
            ],

        ],
    ]); 
    
$this->registerJs('

    $(".pjaxDelete").on("click", function (e) {
        /* cegah tautan menjalankan default action */
        e.preventDefault();
        if(confirm("Are you sure you want to delete this item?")){
            /* request actionDelete dengan method post */
            $.post($(this).attr("href"), function(data) {
                /* reload gridview */
                $.pjax.reload("#gridview",{"timeout":false});
            });
        }
    });

    $("#categoryModal").on("shown.bs.modal", function (event) {
        var button = $(event.relatedTarget)
        var href = button.attr("href")
        $.pjax.reload("#pjax-modal",{
            "timeout":false,
            "url": href, 
            "replace": false,
        });
    })

');
    

// $this->registerJs('
//     var currentData = "";
//     var check = function(){
//         setTimeout(function(){
//             $.ajax({ url: "'.Url::to(['category/check']).'", success: function(data){
//                 if(currentData!=data.lastId){
//                     currentData = data.lastId;    
//                     $.pjax({
//                         url:"'.Url::to(['category/index']).'",
//                         container:"#gridview",
//                         timeout:false,
//                         replace: false,
//                     }).done(function(data) { 
//                         check();
//                     });
//                 }
//                 else{
//                     check();
//                 }
//             }, dataType: "json"});
//         }, 5000);
//     }
//     check();
// ');

   
?>


<?php \yii\widgets\Pjax::end() ?>
</div>

views/category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = 'Update Category: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="category-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="category-view">
    <?= Html::a('Back', ['index'], ['class' => 'btn btn-success',
        'onclick'=>'
          $("#categoryModal").modal("hide");
          return false;
        '
    ]) 
    ?>
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'created_at',
            'updated_at',

        ],
    ]) ?>

</div>